/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 * @author Kitsumyuzu
 */

import javax.swing.*;
import java.awt.*;

public class Kalkulator extends javax.swing.JFrame {

    private double currentResult;
    private String currentInput;
    private String lastInput;

    /**
     * Creates new form Kalkulator
     */

    public Kalkulator() {
        initComponents();
        currentResult = 0;
        currentInput = "";
        lastInput = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("checked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_panel = new javax.swing.JPanel();
        clear_button = new javax.swing.JButton();
        percent_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        divide_button = new javax.swing.JButton();
        times_button = new javax.swing.JButton();
        minus_button = new javax.swing.JButton();
        plus_button = new javax.swing.JButton();
        equal_button = new javax.swing.JButton();
        num_one_button = new javax.swing.JButton();
        num_two_button = new javax.swing.JButton();
        num_three_button = new javax.swing.JButton();
        num_four_button = new javax.swing.JButton();
        num_five_button = new javax.swing.JButton();
        num_six_button = new javax.swing.JButton();
        num_seven_button = new javax.swing.JButton();
        num_eight_button = new javax.swing.JButton();
        num_nine_button = new javax.swing.JButton();
        sym_koma_button = new javax.swing.JButton();
        num_doublezero_button = new javax.swing.JButton();
        num_zero_button = new javax.swing.JButton();
        toggle_on_off_button = new javax.swing.JButton();
        result_panel = new javax.swing.JPanel();
        result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_panel.setBackground(new java.awt.Color(0, 0, 0));

        clear_button.setBackground(new java.awt.Color(60, 60, 60));
        clear_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        clear_button.setForeground(new java.awt.Color(255, 255, 255));
        clear_button.setText("C");
        clear_button.setBorderPainted(false);
        clear_button.setEnabled(false);
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        percent_button.setBackground(new java.awt.Color(60, 60, 60));
        percent_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        percent_button.setForeground(new java.awt.Color(255, 255, 255));
        percent_button.setText("%");
        percent_button.setBorderPainted(false);
        percent_button.setEnabled(false);
        percent_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percent_buttonActionPerformed(evt);
            }
        });

        delete_button.setBackground(new java.awt.Color(60, 60, 60));
        delete_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        delete_button.setForeground(new java.awt.Color(255, 255, 255));
        delete_button.setText("<=");
        delete_button.setBorderPainted(false);
        delete_button.setEnabled(false);
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        divide_button.setBackground(new java.awt.Color(60, 60, 60));
        divide_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        divide_button.setForeground(new java.awt.Color(255, 255, 255));
        divide_button.setText("/");
        divide_button.setBorderPainted(false);
        divide_button.setEnabled(false);
        divide_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divide_buttonActionPerformed(evt);
            }
        });

        times_button.setBackground(new java.awt.Color(60, 60, 60));
        times_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        times_button.setForeground(new java.awt.Color(255, 255, 255));
        times_button.setText("X");
        times_button.setBorderPainted(false);
        times_button.setEnabled(false);
        times_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                times_buttonActionPerformed(evt);
            }
        });

        minus_button.setBackground(new java.awt.Color(60, 60, 60));
        minus_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        minus_button.setForeground(new java.awt.Color(255, 255, 255));
        minus_button.setText("-");
        minus_button.setBorderPainted(false);
        minus_button.setEnabled(false);
        minus_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minus_buttonActionPerformed(evt);
            }
        });

        plus_button.setBackground(new java.awt.Color(60, 60, 60));
        plus_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        plus_button.setForeground(new java.awt.Color(255, 255, 255));
        plus_button.setText("+");
        plus_button.setBorderPainted(false);
        plus_button.setEnabled(false);
        plus_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_buttonActionPerformed(evt);
            }
        });

        equal_button.setBackground(new java.awt.Color(255, 102, 0));
        equal_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        equal_button.setForeground(new java.awt.Color(255, 255, 255));
        equal_button.setText("=");
        equal_button.setBorderPainted(false);
        equal_button.setEnabled(false);
        equal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equal_buttonActionPerformed(evt);
            }
        });

        num_one_button.setBackground(new java.awt.Color(41, 40, 40));
        num_one_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        num_one_button.setForeground(new java.awt.Color(255, 255, 255));
        num_one_button.setText("1");
        num_one_button.setBorderPainted(false);
        num_one_button.setEnabled(false);
        num_one_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_one_buttonActionPerformed(evt);
            }
        });

        num_two_button.setBackground(new java.awt.Color(41, 40, 40));
        num_two_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        num_two_button.setForeground(new java.awt.Color(255, 255, 255));
        num_two_button.setText("2");
        num_two_button.setBorderPainted(false);
        num_two_button.setEnabled(false);
        num_two_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_two_buttonActionPerformed(evt);
            }
        });

        num_three_button.setBackground(new java.awt.Color(41, 40, 40));
        num_three_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        num_three_button.setForeground(new java.awt.Color(255, 255, 255));
        num_three_button.setText("3");
        num_three_button.setBorderPainted(false);
        num_three_button.setEnabled(false);
        num_three_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_three_buttonActionPerformed(evt);
            }
        });

        num_four_button.setBackground(new java.awt.Color(41, 40, 40));
        num_four_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        num_four_button.setForeground(new java.awt.Color(255, 255, 255));
        num_four_button.setText("4");
        num_four_button.setBorderPainted(false);
        num_four_button.setEnabled(false);
        num_four_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_four_buttonActionPerformed(evt);
            }
        });

        num_five_button.setBackground(new java.awt.Color(41, 40, 40));
        num_five_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        num_five_button.setForeground(new java.awt.Color(255, 255, 255));
        num_five_button.setText("5");
        num_five_button.setBorderPainted(false);
        num_five_button.setEnabled(false);
        num_five_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_five_buttonActionPerformed(evt);
            }
        });

        num_six_button.setBackground(new java.awt.Color(41, 40, 40));
        num_six_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        num_six_button.setForeground(new java.awt.Color(255, 255, 255));
        num_six_button.setText("6");
        num_six_button.setBorderPainted(false);
        num_six_button.setEnabled(false);
        num_six_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_six_buttonActionPerformed(evt);
            }
        });

        num_seven_button.setBackground(new java.awt.Color(41, 40, 40));
        num_seven_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        num_seven_button.setForeground(new java.awt.Color(255, 255, 255));
        num_seven_button.setText("7");
        num_seven_button.setBorderPainted(false);
        num_seven_button.setEnabled(false);
        num_seven_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_seven_buttonActionPerformed(evt);
            }
        });

        num_eight_button.setBackground(new java.awt.Color(41, 40, 40));
        num_eight_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        num_eight_button.setForeground(new java.awt.Color(255, 255, 255));
        num_eight_button.setText("8");
        num_eight_button.setBorderPainted(false);
        num_eight_button.setEnabled(false);
        num_eight_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_eight_buttonActionPerformed(evt);
            }
        });

        num_nine_button.setBackground(new java.awt.Color(41, 40, 40));
        num_nine_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        num_nine_button.setForeground(new java.awt.Color(255, 255, 255));
        num_nine_button.setText("9");
        num_nine_button.setBorderPainted(false);
        num_nine_button.setEnabled(false);
        num_nine_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_nine_buttonActionPerformed(evt);
            }
        });

        sym_koma_button.setBackground(new java.awt.Color(41, 40, 40));
        sym_koma_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        sym_koma_button.setForeground(new java.awt.Color(255, 255, 255));
        sym_koma_button.setText(".");
        sym_koma_button.setBorderPainted(false);
        sym_koma_button.setEnabled(false);
        sym_koma_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sym_koma_buttonActionPerformed(evt);
            }
        });

        num_doublezero_button.setBackground(new java.awt.Color(41, 40, 40));
        num_doublezero_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        num_doublezero_button.setForeground(new java.awt.Color(255, 255, 255));
        num_doublezero_button.setText("00");
        num_doublezero_button.setBorderPainted(false);
        num_doublezero_button.setEnabled(false);
        num_doublezero_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_doublezero_buttonActionPerformed(evt);
            }
        });

        num_zero_button.setBackground(new java.awt.Color(41, 40, 40));
        num_zero_button.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        num_zero_button.setForeground(new java.awt.Color(255, 255, 255));
        num_zero_button.setText("0");
        num_zero_button.setBorderPainted(false);
        num_zero_button.setEnabled(false);
        num_zero_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_zero_buttonActionPerformed(evt);
            }
        });

        toggle_on_off_button.setBackground(new java.awt.Color(255, 0, 0));
        toggle_on_off_button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        toggle_on_off_button.setForeground(new java.awt.Color(255, 255, 255));
        toggle_on_off_button.setText("ON / OFF");
        toggle_on_off_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle_on_off_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout button_panelLayout = new javax.swing.GroupLayout(button_panel);
        button_panel.setLayout(button_panelLayout);
        button_panelLayout.setHorizontalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toggle_on_off_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(button_panelLayout.createSequentialGroup()
                        .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(percent_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divide_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(button_panelLayout.createSequentialGroup()
                        .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, button_panelLayout.createSequentialGroup()
                                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(num_seven_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num_four_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(num_five_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num_eight_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(button_panelLayout.createSequentialGroup()
                                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(num_one_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num_doublezero_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(num_zero_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num_two_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sym_koma_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num_six_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num_nine_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num_three_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(equal_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minus_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(times_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plus_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        button_panelLayout.setVerticalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toggle_on_off_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percent_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divide_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(num_seven_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num_eight_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(num_nine_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(times_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minus_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num_six_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num_five_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num_four_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(num_three_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num_two_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num_one_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plus_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(equal_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sym_koma_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num_zero_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num_doublezero_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(button_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 330, -1));

        result_panel.setBackground(new java.awt.Color(0, 0, 0));
        result_panel.setForeground(new java.awt.Color(255, 255, 255));

        result.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));
        result.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        result.setText("0");

        javax.swing.GroupLayout result_panelLayout = new javax.swing.GroupLayout(result_panel);
        result_panel.setLayout(result_panelLayout);
        result_panelLayout.setHorizontalGroup(
            result_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, result_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );
        result_panelLayout.setVerticalGroup(
            result_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, result_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(result_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toggle_on_off_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        if (toggle_on_off_button.getBackground().equals(hexToColor("#FF0000"))) {

            toggle_on_off_button.setBackground(hexToColor("#00FF00"));

        // Calculator System Button

            clear_button.setEnabled(true);
            percent_button.setEnabled(true);
            delete_button.setEnabled(true);
            divide_button.setEnabled(true);
            times_button.setEnabled(true);
            minus_button.setEnabled(true);
            plus_button.setEnabled(true);
            equal_button.setEnabled(true);

        // Number Button

            num_nine_button.setEnabled(true);
            num_eight_button.setEnabled(true);
            num_seven_button.setEnabled(true);

            num_six_button.setEnabled(true);
            num_five_button.setEnabled(true);
            num_four_button.setEnabled(true);

            num_three_button.setEnabled(true);
            num_two_button.setEnabled(true);
            num_one_button.setEnabled(true);

            num_doublezero_button.setEnabled(true);
            num_zero_button.setEnabled(true);
            sym_koma_button.setEnabled(true);

            result.setText("0");

        } else {

            toggle_on_off_button.setBackground(hexToColor("#FF0000"));

        // Calculator System Button

            clear_button.setEnabled(false);
            percent_button.setEnabled(false);
            delete_button.setEnabled(false);
            divide_button.setEnabled(false);
            times_button.setEnabled(false);
            minus_button.setEnabled(false);
            plus_button.setEnabled(false);
            equal_button.setEnabled(false);

        // Number Button

            num_nine_button.setEnabled(false);
            num_eight_button.setEnabled(false);
            num_seven_button.setEnabled(false);

            num_six_button.setEnabled(false);
            num_five_button.setEnabled(false);
            num_four_button.setEnabled(false);

            num_three_button.setEnabled(false);
            num_two_button.setEnabled(false);
            num_one_button.setEnabled(false);

            num_doublezero_button.setEnabled(false);
            num_zero_button.setEnabled(false);
            sym_koma_button.setEnabled(false);

            result.setText("0");

        }

    }

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        result.setText("0");

    }

    private void percent_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        


    }

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        String resulttext = result.getText();

        // Membuat sebuah kondisi dimana jika resulttext memiliki value maka dikurangkan 1 angka yang telah di input

            if (!resulttext.equals("0")) {
                if (resulttext.length() > 1) {
                    result.setText(resulttext.substring(0, resulttext.length() - 1));
                } else {
                    result.setText("0");
                }
            } else {
                result.setText("0");
            }

    }

    private void divide_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        


    }

    private void times_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        


    }

    private void minus_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        


    }

    private void plus_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        


    }

    private void equal_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        


    }

    private void sym_koma_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay(".");

    }

    private void num_zero_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay("0");

    }

    private void num_doublezero_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay("00");

    }

    private void num_three_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay("3");

    }

    private void num_two_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay("2");

    }

    private void num_one_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay("1");

    }

    private void num_six_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay("6");

    }

    private void num_five_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay("5");

    }

    private void num_four_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay("4");

    }

    private void num_nine_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay("9");

    }

    private void num_eight_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay("8");

    }

    private void num_seven_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        
        updateDisplay("7");

    }

    // Change hex code value into a color value

        private static Color hexToColor(String hexCode) {
            return Color.decode(hexCode);
        }

    // Update the value

        private boolean filter_koma = false;

        private void updateDisplay(String value) {
            String currentText = result.getText();
        
            if (currentText.equals("0")) {
                // Jika tampilan hanya menunjukkan "0" dan tombol koma ditekan,
                // tambahkan koma di depan "0"
                if (value.equals(".") && !filter_koma) {
                    result.setText("0" + value);
                    filter_koma = true;
                } else if (!value.equals(".")) {
                    // Ganti "0" dengan digit yang ditekan
                    result.setText(value);
                }
            } else {
                // Tambahkan digit yang ditekan ke teks tampilan saat ini
                if (!filter_koma || !value.equals(".")) {
                    result.setText(currentText + value);
        
                    // Jika koma dimasukkan, set variabel menjadi true
                    if (value.equals(".")) {
                        filter_koma = true;
                    }
                }
            }
        }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button_panel;
    private javax.swing.JButton clear_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton divide_button;
    private javax.swing.JButton equal_button;
    private javax.swing.JButton minus_button;
    private javax.swing.JButton num_doublezero_button;
    private javax.swing.JButton num_eight_button;
    private javax.swing.JButton num_five_button;
    private javax.swing.JButton num_four_button;
    private javax.swing.JButton num_nine_button;
    private javax.swing.JButton num_one_button;
    private javax.swing.JButton num_seven_button;
    private javax.swing.JButton num_six_button;
    private javax.swing.JButton num_three_button;
    private javax.swing.JButton num_two_button;
    private javax.swing.JButton num_zero_button;
    private javax.swing.JButton percent_button;
    private javax.swing.JButton plus_button;
    private javax.swing.JLabel result;
    private javax.swing.JPanel result_panel;
    private javax.swing.JButton sym_koma_button;
    private javax.swing.JButton times_button;
    private javax.swing.JButton toggle_on_off_button;
    // End of variables declaration//GEN-END:variables
}
